[package]
authors.workspace = true
name = "cumulus-relay-chain-interface"
version = "0.7.0"
edition.workspace = true
description = "Common interface for different relay chain datasources."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
polkadot-overseer = { workspace = true, default-features = true }

cumulus-primitives-core = { workspace = true, default-features = true }

sp-api = { path = "../../../substrate/primitives/api" }
sp-blockchain = { path = "../../../substrate/primitives/blockchain" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sc-client-api = { path = "../../../substrate/client/api" }
sp-version = { path = "../../../substrate/primitives/version", default-features = false }

futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
jsonrpsee-core = { workspace = true }
codec = { workspace = true, default-features = true }
