[package]
name = "cumulus-client-pov-recovery"
version = "0.7.0"
authors.workspace = true
description = "Cumulus-specific networking protocol"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
rand = { workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }

# Substrate
sc-client-api = { path = "../../../substrate/client/api" }
sc-consensus = { path = "../../../substrate/client/consensus/common" }
sp-consensus = { path = "../../../substrate/primitives/consensus/common" }
sp-maybe-compressed-blob = { path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-api = { path = "../../../substrate/primitives/api" }
sp-version = { path = "../../../substrate/primitives/version" }

# Polkadot
polkadot-node-primitives = { workspace = true, default-features = true }
polkadot-node-subsystem = { workspace = true, default-features = true }
polkadot-overseer = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-relay-chain-interface = { workspace = true, default-features = true }
async-trait = { workspace = true }

[dev-dependencies]
rstest = "0.18.2"
tokio = { version = "1.32.0", features = ["macros"] }
portpicker = "0.1.1"
sp-blockchain = { path = "../../../substrate/primitives/blockchain" }
cumulus-test-client = { path = "../../test/client" }
sc-utils = { path = "../../../substrate/client/utils" }
sp-tracing = { path = "../../../substrate/primitives/tracing" }
assert_matches = "1.5"

# Cumulus
cumulus-test-service = { workspace = true }

# Substrate
sc-cli = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
substrate-test-utils = { workspace = true }
