[package]
name = "cumulus-client-network"
version = "0.7.0"
authors.workspace = true
description = "Cumulus-specific networking protocol"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
futures-timer = { workspace = true }
parking_lot = { workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }

# Substrate
sc-client-api = { path = "../../../substrate/client/api" }
sp-blockchain = { path = "../../../substrate/primitives/blockchain" }
sp-consensus = { path = "../../../substrate/primitives/consensus/common" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sp-api = { path = "../../../substrate/primitives/api" }
sp-version = { path = "../../../substrate/primitives/version" }

# Polkadot
polkadot-node-primitives = { path = "../../../polkadot/node/primitives" }
polkadot-parachain-primitives = { path = "../../../polkadot/parachain" }
polkadot-primitives = { path = "../../../polkadot/primitives" }
polkadot-node-subsystem = { path = "../../../polkadot/node/subsystem" }

# Cumulus
cumulus-relay-chain-interface = { workspace = true, default-features = true }

[dev-dependencies]
portpicker = "0.1.1"
tokio = { version = "1.32.0", features = ["macros"] }
url = "2.4.0"
rstest = "0.18.2"

# Substrate
sc-cli = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sp-consensus = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
substrate-test-utils = { workspace = true }

# Polkadot
polkadot-test-client = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-relay-chain-inprocess-interface = { workspace = true, default-features = true }
cumulus-test-service = { workspace = true }
