[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
codec = { features = ["derive"], workspace = true, default-features = true }
dyn-clone = { workspace = true }
futures = { workspace = true }
log = { workspace = true, default-features = true }
tracing = { workspace = true, default-features = true }

# Substrate
sc-client-api = { path = "../../../../substrate/client/api" }
sc-consensus = { path = "../../../../substrate/client/consensus/common" }
sc-consensus-babe = { path = "../../../../substrate/client/consensus/babe" }
sp-blockchain = { path = "../../../../substrate/primitives/blockchain" }
sp-consensus = { path = "../../../../substrate/primitives/consensus/common" }
sp-consensus-slots = { path = "../../../../substrate/primitives/consensus/slots" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-runtime = { path = "../../../../substrate/primitives/runtime" }
sp-timestamp = { path = "../../../../substrate/primitives/timestamp" }
sp-trie = { path = "../../../../substrate/primitives/trie" }
sp-version = { path = "../../../../substrate/primitives/version" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../../substrate/utils/prometheus" }

# Polkadot
polkadot-primitives = { workspace = true, default-features = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = true }
cumulus-relay-chain-interface = { workspace = true, default-features = true }
cumulus-client-pov-recovery = { workspace = true, default-features = true }
schnellru = { workspace = true }

[dev-dependencies]
futures-timer = { workspace = true }

# Substrate
sp-tracing = { workspace = true, default-features = true }

# Cumulus
cumulus-test-client = { workspace = true }
cumulus-test-relay-sproof-builder = { workspace = true, default-features = true }
