[package]
name = "substrate-frame-rpc-system"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.30"
codec = { package = "parity-scale-codec", version = "3.6.12" }
docify = "0.2.0"
jsonrpsee = { version = "0.22.5", features = [
	"client-core",
	"macros",
	"server-core",
] }
log = { workspace = true, default-features = true }
frame-system-rpc-runtime-api = { workspace = true, default-features = true }
sc-rpc-api = { workspace = true, default-features = true }
sc-transaction-pool-api = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[dev-dependencies]
sc-transaction-pool = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true }
assert_matches = { workspace = true }
sp-tracing = { workspace = true, default-features = true }
substrate-test-runtime-client = { workspace = true }
