[package]
name = "cumulus-client-chain-spec-extension"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Parachain chain-spec extension."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
sc-chain-spec = { path = "../../../substrate/client/chain-spec" }
serde = { features = ["derive"], workspace = true, default-features = true }
